name: Update Version

on:
  push:
    branches:
      - master

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Get the number of pull requests
        id: pr_count
        run: echo "PR_COUNT=$(curl -s https://api.github.com/repos/${{ github.repository }}/pulls?state=all | jq '. | length')" >> $GITHUB_ENV

      - name: Get the total commits
        id: commit_count
        run: echo "COMMIT_COUNT=$(git rev-list --count HEAD)" >> $GITHUB_ENV

      - name: Update version in HTML
        run: |
          VERSION="1.$PR_COUNT.$COMMIT_COUNT"
          sed -i "s/version-placeholder/$VERSION/g" index.html  # Ensure the path is correct

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "actions@github.com"
          git add index.html
          git commit -m "Update version to $VERSION"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
